### PR TITLE
Fix assign role command to handle adding multiple roles

### LINKED ISSUE #138: Assign role command does not correctly add multiple roles

### PR DESCRIPTION
**Pull request by Glenn-Chiang**
Closes #138

### CODE REVIEW

File: src/main/java/seedu/excolink/logic/commands/AssignRoleCommand.java [hunk 1]
```diff
@@ -51,10 +61,13 @@ public CommandResult execute(Model model) throws CommandException {
 
         Person personToEdit = lastShownList.get(index.getZeroBased());
 
+
         Set<Role> personRoles = new HashSet<>(personToEdit.getRoles());
 
-        if (!personRoles.add(role)) {
-            throw new CommandException(String.format(MESSAGE_DUPLICATE_ROLE, personToEdit.getName(), role));
+        for (Role role: rolesToAdd) {
```
Comment (Sengernest) [inline src/main/java/seedu/excolink/logic/commands/AssignRoleCommand.java:67]: Good implementation of iterating through the roles to ensure no duplicates

**Review by Sengernest — APPROVED** [review]
Overall LGTM, perhaps more testing is needed.
