### PR TITLE
Fix delete role command to handle deleting multiple roles

### LINKED ISSUE #139: Delete role command does not correctly delete multiples roles

### PR DESCRIPTION
**Pull request by Glenn-Chiang**
Closes #139

### CODE REVIEW

File: src/test/java/seedu/excolink/logic/commands/DeleteRoleCommandTest.java [hunk 1]
```diff
@@ -54,7 +54,7 @@ public void execute_validRole_success() throws CommandException {
         CommandResult result = command.execute(model);
 
         String expectedMessage = String.format(DeleteRoleCommand.MESSAGE_SUCCESS,
-                testPerson.getName(), existingRole.roleName);
+                testPerson.getName(), existingRole);
```
Comment (weijie-wang227) [inline src/test/java/seedu/excolink/logic/commands/DeleteRoleCommandTest.java:57]: Good job keeping it consistent

File: src/main/java/seedu/excolink/logic/parser/DeleteRoleCommandParser.java [hunk 2]
```diff
@@ -25,9 +27,9 @@ public DeleteRoleCommand parse(String args) throws ParseException {
             String preamble = argMultimap.getPreamble().trim();
             Index index = ParserUtil.parseIndex(preamble);
 
-            Role role = ParserUtil.parseRole(argMultimap.getValue(PREFIX_ROLE).get());
+            Set<Role> roles = ParserUtil.parseRoles(argMultimap.getAllValues(PREFIX_ROLE));
```
Comment (weijie-wang227) [inline src/main/java/seedu/excolink/logic/parser/DeleteRoleCommandParser.java:30]: Good job keeping it consistent with add roles

File: src/main/java/seedu/excolink/logic/commands/DeleteRoleCommand.java [hunk 3]
```diff
@@ -39,7 +40,17 @@ public DeleteRoleCommand(Index index, Role role) {
         requireNonNull(index);
         requireNonNull(role);
         this.index = index;
-        this.role = role;
+        this.rolesToDelete = Set.of(role);
```
Comment (weijie-wang227) [inline src/main/java/seedu/excolink/logic/commands/DeleteRoleCommand.java:43]: Great job using overloading to keep previous iterations consistent

File: src/main/java/seedu/excolink/logic/commands/DeleteRoleCommand.java [hunk 4]
```diff
@@ -54,19 +65,14 @@ public CommandResult execute(Model model) throws CommandException {
...
+        Set<Role> existingRoles = personToEdit.getRoles();
+        Set<Role> updatedRoles = new HashSet<>(existingRoles);
 
-        if (!roleFound) {
-            throw new CommandException(String.format(MESSAGE_ROLE_NOT_FOUND, role.roleName));
+        for (Role roleToDelete: rolesToDelete) {
+            if (!existingRoles.contains(roleToDelete)) {
+                throw new CommandException(String.format(MESSAGE_ROLE_NOT_FOUND, roleToDelete));
+            }
+            updatedRoles.remove(roleToDelete);
```
Comment (weijie-wang227) [inline src/main/java/seedu/excolink/logic/commands/DeleteRoleCommand.java:75]: Nice job creating a new set for updated roles so person object is only affected when all the roles are looped through

**Review by weijie-wang227 — APPROVED** [review]
Nicely done
