### PR TITLE
Fix AssignRoleCommand to error on duplicate role

### LINKED ISSUE #137: Assign role command does not handle duplicate roles

### PR DESCRIPTION
**Pull request by Glenn-Chiang**
Closes #137

### CODE REVIEW

File: src/main/java/seedu/excolink/logic/commands/AssignRoleCommand.java [hunk 1]
```diff
@@ -50,14 +51,17 @@ public CommandResult execute(Model model) throws CommandException {
 
         Person personToEdit = lastShownList.get(index.getZeroBased());
 
-        Set<Role> updatedRoles = new HashSet<>(personToEdit.getRoles());
-        updatedRoles.add(role);
+        Set<Role> personRoles = new HashSet<>(personToEdit.getRoles());
```
Comment (Sengernest) [inline src/main/java/seedu/excolink/logic/commands/AssignRoleCommand.java:54]: Good use of hashset to determine duplicates

File: src/test/java/seedu/excolink/logic/commands/AssignRoleCommandTest.java [hunk 2]
```diff
@@ -56,6 +57,29 @@ public void execute_validIndex_success() throws CommandException {
         Person updatedPerson = model.getFilteredPersonList().get(0);
         assertEquals(Collections.singleton(role), updatedPerson.getRoles());
     }
+    @Test
+    public void execute_duplicateRole_throwsCommandException() {
```
Comment (Sengernest) [inline src/test/java/seedu/excolink/logic/commands/AssignRoleCommandTest.java:61]: Good that you updated the test case to test for duplicates.

**Review by Sengernest — APPROVED** [review]
Overall LGTM, good job spotting the duplicate bug
