### PR TITLE
Fix list display entity

### LINKED ISSUE #159: List remains filtered when changing list display entity
Steps to reproduce:
- Filter the person list
- List subcoms
- While subcom list is still displayed, perform a person operation using an index that is out of range of the previously filtered person list.
- Error: Person index provided is invalid

Question: should we even be able to operate on indices that are not on the current screen?

Suggested fix:
- When the current display entity is subcom and the user executes a command requiring a person index, prompt the user to switch to the person list
- When the current display entity is person and the user executes a command requiring a subcom index, prompt the user to switch to the subcom list

### PR DESCRIPTION
**Pull request by Glenn-Chiang**
Fixes #159

Warn the user to switch to the correct list.

### CODE REVIEW

File: src/main/java/seedu/excolink/logic/Messages.java [hunk 1]
```diff
@@ -21,6 +21,10 @@ public class Messages {
     public static final String MESSAGE_DUPLICATE_FIELDS =
                 "Multiple values specified for the following single-valued field(s): ";
     public static final String MESSAGE_INVALID_SUBCOM_NAME = "The subcommittee provided does not exist";
+    public static final String MESSAGE_WRONG_DISPLAY_ENTITY_FOR_PERSON_COMMAND =
+            "This command cannot be used in the current view. Please switch to the person list first.";
```
Comment (weijie-wang227) [inline src/main/java/seedu/excolink/logic/Messages.java]: I think it might be helpful to put the command to switch also

**Review by weijie-wang227 — COMMENTED** [review]
Small request

File: src/main/java/seedu/excolink/logic/Messages.java (hunk 1 above)
Comment (Glenn-Chiang) [reply src/main/java/seedu/excolink/logic/Messages.java]: good idea

File: src/test/java/seedu/excolink/logic/commands/AssignRoleCommandTest.java [hunk 2]
```diff
@@ -94,6 +96,23 @@ public void execute_invalidIndex_throwsCommandException() {
...
     }
 
+    @Test
+    public void execute_wrongDisplayEntity_throwsCommandException() {
+        model.setDisplayEntity(DisplayEntity.SUBCOM);
+        Index index = Index.fromOneBased(1);
+        Role role = new Role("Treasurer");
+        AssignRoleCommand command = new AssignRoleCommand(index, role);
+
+        try {
```
Comment (Sengernest) [inline src/test/java/seedu/excolink/logic/commands/AssignRoleCommandTest.java:106]: Good error handling

**Review by Sengernest — APPROVED** [review]
LGTM, good use of error handling techniques
