### PR TITLE
Bug/overzealous phone input

### LINKED ISSUE #252: [PE-D][Tester D] Overzealous input validation for phone number
Image

There might be overzealous input validation for phone number. For example, phone numbers like '+65 9876 5432' are not allowed, and rejecting such inputs might annoy or inconvenience the user.

Steps
1. Performing `add n/John Doe p/+65 98765432 (Home) e/johnd@example.com r/Team Lead`
2.  The app responds with 'Phone numbers should only contain numbers, and it should be at least 3 digits long.'

The app requires that 'Phone numbers should only contain numbers, and it should be at least 3 digits long.' However, this might be considered as overzealous input validation. For example a user might want to add '+65 98765432 (Home)' as the person's phone number. Blocking that input might not add any value but allowing it does. Hence, the team could consider accepting such symbols.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### PR DESCRIPTION
**Pull request by Whyudothiss**
Fixes #252

### CODE REVIEW

File: src/main/java/seedu/excolink/model/person/Phone.java [hunk 1]
```diff
@@ -11,8 +11,10 @@ public class Phone {
 
 
     public static final String MESSAGE_CONSTRAINTS =
-            "Phone numbers should only contain numbers, and it should be at least 3 digits long";
-    public static final String VALIDATION_REGEX = "\\d{3,}";
+            "Phone numbers should be at least 3 characters long";
+    public static final String MESSAGE_NON_NUMERIC_WARNING =
+            "Warning: Phone number contains non-numeric characters, which may not follow standard conventions.";
```
Comment (Glenn-Chiang) [inline src/main/java/seedu/excolink/model/person/Phone.java:16]: Good warning text

**Review by Glenn-Chiang — APPROVED** [review]
LGTM
