### PR TITLE
Fix list subcom members success message casing

### LINKED ISSUE #158: ListSubcomMembers success message is in incorrect case
Success message shown when listing subcom members should be capital letters for Subcommittee to follow rest of code.

### PR DESCRIPTION
**Pull request by Glenn-Chiang**
Fixes #158

### CODE REVIEW

File: src/test/java/seedu/excolink/logic/commands/ListSubcomMembersCommandTest.java [hunk 1]
```diff
@@ -88,6 +91,15 @@ public boolean hasSubcom(Subcom subcom) {
             return subcoms.stream().anyMatch(s -> s.equals(subcom));
         }
 
+        @Override
+        public Subcom findSubcom(Subcom subcom) {
```
Comment (Sengernest) [inline src/test/java/seedu/excolink/logic/commands/ListSubcomMembersCommandTest.java:95]: Good use of streams to make the code easier to read and understand

**Review by Sengernest — APPROVED** [review]
Overall LGTM, good that you made the code easy to read and concise
